name: belajar_dart_library
description: Learning dart library from 'Programmer Zaman Now' youtube channel.
version: 1.2.0

environment:
  sdk: '>=2.18.5 <3.0.0'

# dependencies:
#   path: ^1.8.0

# note : this dependency is only for development
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
